### ISSUE TITLE
Plugin does not show up in menu entry for version  Version 18.1.0.095

### ISSUE THREAD

**Issue by gkapagunta** [tomecode/show-me-password-sqldev-jdev#14]
After installing the plug-in, the "Show Me Password" entry does not get added in the menu options. Tried to remove system_cache folder from AppData and restarted, issue persists.

**Comment by tomecode** [comment]
fixed in #16 - release: [Show Me Password for SQL Developer (version: 18)
](https://github.com/tomecode/show-me-password-sqldev-jdev/releases/download/%2316/ShowMePasswordSQLDeveloper-18c_v2.0.0.zip)
