### ISSUE TITLE
Any push for a 20X/21X version...?

### ISSUE THREAD

**Issue by bostonareahuman** [tomecode/show-me-password-sqldev-jdev#20]
Just wondering since it appears not work with 20/21...thanks

**Comment by denymen** [comment]
Hello, It is working for me with the 23.1 as well.

**Comment by ahmed527** [comment]
@denymen 
did you do something special? I do not see the option in the menu and I have the latest version of SQL developer v21.

**Comment by tomecode** [comment]
it still works in version 23 
![image](https://github.com/tomecode/show-me-password-sqldev-jdev/assets/6022988/14aeb82c-0c49-47b2-bd7f-40ddaa2a23c9)

**Comment by denymen** [comment]
> @denymen did you do something special? I do not see the option in the menu and I have the latest version of SQL developer v21.

no, it is just working.

**Comment by tomecode** [comment]
Let me know if there are any issues, and I will try to fix them ;)
