### ISSUE TITLE
Missing build script?

### ISSUE THREAD

**Issue by albertogarza** [tomecode/show-me-password-sqldev-jdev#3]
I was looking through your code on github and could not find a way to build it myself right out of the box. Perhaps I missed it. I wanted to do that because I saw your README file's link to the downloadable zip file still points to your old project's googlecode.com repo. I think it would be nice to have your build script (ant, maven, or whatever)  to build the github project ourselves and possibly provide pull requests and help you out if needed. Regardless of what you decide to do, thanks for sharing your work! This has saved me significant pain and time.

**Comment by tomecode** [comment]
Hi Alberto,
thanks for the note, I have updated  README file, but the problem with build script is that this is JDEV project, and that type of project not support the ant. maven etc.
