### ISSUE TITLE
Can't install on Win7 / SQLdev 4.1

### ISSUE THREAD

**Issue by markl181** [tomecode/show-me-password-sqldev-jdev#7]
I've followed the steps but there is no menu item added for show me password, which makes me think it's not installing. If I follow the exact same steps on OS X, it works fine. Is there anything I can do to troubleshoot this?

**Comment by Shoelace** [comment]
it works for me on sqldeveloper 4.1.5 under windows 7

the menu option is under the File menu.. 
ie File->Show Me Password



![image](https://cloud.githubusercontent.com/assets/391364/20428249/ec457b6a-ad7f-11e6-98b5-4133c0919824.png)

also you can check if "Show Me Password" is listed under the loaded extenstions. goto Help->about theneth extensions tab 

![image](https://cloud.githubusercontent.com/assets/391364/20428281/1ced3a28-ad80-11e6-80e2-e84e663fc3b4.png)

**Comment by tomecode** [comment]
I know that sometimes it does not work on Linux/Windows or Mac, but I don't know why. I tried to reproduce this problem, but I have not been successful.

**Comment by markl181** [comment]
Thanks @tomecode, is there any way to troubleshoot this, like adding an installation log?

**Comment by tomecode** [comment]
@markl181 I don't know, becasue the installation is completely done by SQLDeveloper,..
