### ISSUE TITLE
Does not work in Oracle SQL Developer 4.1.5.21

### ISSUE THREAD

**Issue by steven-simmons** [tomecode/show-me-password-sqldev-jdev#8]
I have tried installing the extension in SQL Dev 4.1.5 using your instructions, both as a regular user and as an administrator.  I can not find the extension in any menu.  I also tried just copying the jar file to the extensions directory with the same result.

I used ShowMePasswordSQLDeveloper4_v1.0.0.zip downloaded from your website.

If I can provide any additional info to help debug this, please let me know.

**Comment by tomecode** [comment]
Hi,
 I know that sometimes it happens, but I don't know why, so could you pls. delete: _C:\Users\<user name>\AppData\Roaming\SQL Developer\_ and restart the SQLDeveloper and install the extension

**Comment by markl181** [comment]
Make sure you take a backup of the folder, this is where all your SQL Developer preferences (including all your connections) are stored. I tried this and it didn't make any difference.

**Comment by steven-simmons** [comment]
I had the same result after deleting the folder.  Tried it twice.  There must be something about 4.1.5 that broke your extension.

**Comment by steven-simmons** [comment]
It is working now.  I completely removed Oracle SQL Developer 4.1.5 and re-installed it.  After this, I was able to install ShowMePasswordSQLDeveloper4 as long as I ran SQL Developer as an administrator prior to installation.  The extension continues to work without using admin.  I'm not sure what was wrong before, but a complete uninstall, reboot, install fixed it.

**Comment by markl181** [comment]
@steven-simmons - did you have any connections or preferences to restore, or were you starting completely from scratch? I'd probably try this if I could restore my settings when I do it.

**Comment by steven-simmons** [comment]
I did not save the preferences, but I had exported the connections (with passwords) and used the import tool to put them back prior to installing this extension.

**Comment by tomecode** [comment]
cool:) but is it strange... it seems that something is wrong with sql developer ;)

**Comment by steven-simmons** [comment]
I had 3.2 installed previously and had upgraded to 4.1.5.  Perhaps some garbage settings were retained by the upgrade? A clean install of 4.1.5 along with "run as admin" to install the extension seems to be the trick. You may want to note that in the readme.

**Comment by markl181** [comment]
thanks @steven-simmons , I will test this again shortly. @tomecode btw your website is currently unavailable but I will test once it's back.

**Comment by piotguz** [comment]
Running it in admin mode during installation solved the issue for me!
